# **Data Visualisation**

### Objectives

For this Data Visualisation Jupyter notebook you can expect to see the power of using Matplotlib, Seaborn and Plotly to draw vivid insights from the DataFrames saved at the end of the ETL notebook.

The main objective is to apply Exploratory Data Analysis process onto the DataFrames. I reference questions listed in the hypothesis to reveal meaningfull insights meeting the hypothetical healthcare insurance business requirements.

### Input

The input required for this notebook is listed below.

**File Names:**

> clean_healthcare_insurance.csv

> smokers_charges.csv

**File Paths:**

> (../data/clean/clean_healthcare_insurance.csv)

> (../data/clean/smokers_charges.csv)

### Import Libraries

Import Numpy, Pandas, Matplotlib, Seaborn and Plotly libraries for the EDA process.

In [1]:
import numpy as np # Apply mathematical functions 
import pandas as pd # Load DataFrames
import matplotlib.pyplot as plt # Data visualisation sub-module library 
import seaborn as sns # Statistical data visualisation library 
import plotly.express as px # Interactive data visulisation library
import plotly.io as pio # Manage rendering interactive visualisation

### Load DataFrames

Complete setup for this notebook by loading <code>clean_healthcare_insurance.csv</code> and <code>smoker_charges.csv</code> stored in the data/clean folder.

In [ ]:
# Load clean_healthcare_insurance.csv file
df_insurance = pd.read_csv('../data/clean/clean_healthcare_insurance.csv')

# Print first 5 rows in the DataFrame
df_insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
# Load smokers_charges.csv file 
df_smokers_charges = pd.read_csv('/Users/admin/Documents/Code Institute/vscode-projects/Healthcare-Analysis-Project/Healthcare-Analysis-Project/data/clean/smokers_charges.csv')

# Print DataFrame 
df_smokers_charges

  smoker         min          mean          max
0     no   1121.8739   8440.660307  36910.60803
1    yes  12829.4551  32050.231832  63770.42801

## **Exploratory Data Analysis (EDA)**

In this section the DataFrames will be visualised using a range of charts to communicate meaningfull insights for a healthcare insurance business. 

* **Distribution Analysis:** Understand the distribution of attributes across the dataset. Analysis on distribution is applied in descriptive, predictive, correlation and regional analysis to highlight the integrity of the visualisation.

* **Descriptive Analysis:** A descriptive analysis presents what is contained within the dataset. Distribution is considered in this section using pie or bar charts and boxplots to present an overview on the attributes included in the clean DataFrame. 

* **Correlation Analysis:** Visualise two or more attributes in a scattergraph to analyse the correlation between these attributes in relation to insurance charges. 

* **Regional Analysis:** Determine the difference between regional charges. This analysis can help the insurance company identify attributes within different regions impacting charges. 

* **Predictive Analysis:** Predict charges influenced by attributes such as smokers status. A healthcare insurance business could predict connection with charges in correlation between a range of attributes.

### **Descriptive Analysis**

### **Correlation Analysis**

### **Regional Analysis**

### **Predictive Analsis**

### **Conclusion**